### ISSUE TITLE
feature request: aliases

### ISSUE THREAD

**Issue by 0xJWLabs** [jonasarensmann/Farmer#1]
Hey i don’t know if this already supports alias require. If not, can you add it? and maybe also with sub dependencies support? Thanks!

**Comment by jonasarensmann** [comment]
Hey, alias require is already supported for packages in your project's dependencies. 
1525f801bb04938cb0c4fb367b37f66eee0a0187 reads the farmer.json from depencencies and adds aliases for sub dependencies so they can use alias require without breaking.

**Comment by 0xJWLabs** [comment]
How about the bundling? I don't see it change the require like uhm let's say darklua bundling.

**Comment by jonasarensmann** [comment]
Farmer has a built-in bundler `farmer bundle <output>`, which will bundle your project to the specified path. But it currently does not bundle dependencies with it. I will add that tomorrow or so.

**Comment by jonasarensmann** [comment]
e970f115a40c78b5653b9c43b4b1d1f9894d07da includes dependencies in the bundle when using `farmer bundle <output>`
